### ISSUE TITLE
Zebra_Form as a composer package on Packagist.org

### ISSUE THREAD

**Issue by discopatrick** [stefangabos/Zebra_Form#16]
Hi Stefan. Thanks for following my suggestion and putting a numbered version of Zebra_Form onto packagist.org

The more I use Composer and Packagist, the more I realise how important version numbers are when including libraries like yours in my own projects. If an old build of a project of mine uses a previous version, I need to be able to get that exact same version back in the future.

At the same time, I want to be able to use the latest features and patches in new projects, so please do continue to release further numbered versions onto Packagist.

I look forward to 2.9.6!

**Comment by stefangabos** [comment]
Done!
