### ISSUE TITLE
"Undefined Property" error

### ISSUE THREAD

**Issue by JeffBuckles** [stefangabos/Zebra_Form#21]
Hi, Stefan,
Here's an easy one!

Zebra_Form.php (version 2.9.5)
Line 2741 can give "Undefined Property" in some circumstances
(The control is both locked and disabled to help emulate a "readonly" select input)

```php
    // if control was submitted
    // (as there can also be no selections for a select box with the "multiple" attribute set, case in
    // which there's no submission)
    if ($control->submitted_value) {
```
Seems it should be:

    if (isset($control->submitted_value)) {

?
Thanks and Best Regards,

**Comment by stefangabos** [comment]
Done and thanks for reporting!
