### ISSUE TITLE
Disabled controls retain default value

### ISSUE THREAD

**Issue by JeffBuckles** [stefangabos/Zebra_Form#22]
Our application is designed so that some form controls may not be changed unless the user explicitly "unlocks" them.   For text fields this is very simple: I can set the "readonly" attribute.   However, for checkboxes and select controls, "readonly" is not supported by browsers.   So I must set "disabled".

When the form is submitted it is repainted to allow further editing by the user.  Unfortunately, "disabled" controls repaint with _no_ value instead of the default value because they are not submitted.

The issue seems to be in get_submitted_value() in Control.php , where the sequence of events is:
  if control is not submitted, then submitted_value = false (line 330)
  if isset(submitted_value) then  value = submitted_value (line 423)

I *think* I see a solution, but I'm wary of unintended consequences (for example, how do I distinguish between a disabled checkbox, and one that was un-checked by the user).

One solution is to re-enable all the controls on submit button click (client side).  I'm concerned about visual impact and performance (many controls affected).

Another might be to identify controls not submitted and re-set the value after validation but before rendering (server side).

Have you any suggestions?
Thanks and Best Regards,

**Comment by stefangabos** [comment]
Have you tried using the [lock](http://stefangabos.ro/wp-content/docs/Zebra_Form/Generic/Zebra_Form_Control.html#methodlock) method?

**Comment by JeffBuckles** [comment]
Enable/disable is handled client-side.   In fact my workaround is to have duplicate controls -- the "real", enabled control and a "dummy", locked, disabled control -- and then show/hide the appropriate control depending on the user interaction.   It feels kludgy and inelegant, though.

**Comment by stefangabos** [comment]
This is standard form behavior and not something done by Zebra_Form - disabled elements are simply not submitted by the browser so, yes, you'll have to find a workaround...

**Comment by JeffBuckles** [comment]
Well, one can always hope for a better solution.  Thanks for your feedback.
Best Regards,
