### ISSUE TITLE
Script-Timeout on email field when using malformed email

### ISSUE THREAD

**Issue by ArneTR** [stefangabos/Zebra_Form#24]
Can be reproduced using the Zebra Form demo site with slight modifications.

1. Go to http://stefangabos.ro/wp-content/demos/Zebra_Form/

2. Modify the HTML of the form to have the tag novalidate="true"

3. Enter: "diasndaskndilkasndklasnkdjanjkdnasjkdnasidkaslmndklasndkaskldaskldmklasdklasmkldmaskdmakslmdklasmkdasmkldmaskldmksamkdasmlkdmaskldmkalsmdkmlkdmkasl@google.de                          "

Note: Spaces at the end are important and are what is causing the error.

Result: Script timeout. Screenshot attached.

Having a form with novalidate="true" is not uncommon as the rules applied by browsers differ. We face this issue in a production case. Also some older browsers do not support HTML5 validation of the form and may not be affected too.

Tested in Chrome 48 and FF 48

![screen shot 2016-02-17 at 1 44 02 pm](https://cloud.githubusercontent.com/assets/250671/13109896/920a6ee8-d57c-11e5-968d-48e6394b1919.png)

**Comment by stefangabos** [comment]
Should be fixed now. Thanks!

**Comment by ArneTR** [comment]
Hi Stefan,

my aforementioned test-case works fine now. However, I found another case that does not work.

Use this E-Mail address: "asdjaisufusdiahfjdasbfjhasdnfjksd®bjfhsdbhjfbdsahjfbjhadsbfjhsdabfhjsdbfhjasdbfhjsadbjfbdsakhfjksad@google.de"

This one has no spaces, but a non ascii char in it. This also leads to a script timeout. 

It seems like the regex gets into an infinite loop. You got any idea why that is?

I can also reproduce the problem on http://www.regexpal.com/ using your regex and my given email string address ... if that helps you debugging.

**Comment by stefangabos** [comment]
It seems that the regular expression breaks when the address is very long, although I don't understand why as it doesn't have any fancy expressions in it...

Nevertheless, I made some more changes and it shouldn't break anymore, but know that my validator it is not rfc5321 compliant and will fail for fancy addresses

**Comment by ArneTR** [comment]
I dug into this regex a bit more and must say that I think this regex does more harm than good.

First of all: The initial problem does not occur when using a PCRE regex engine. For example PHP.

If PHP is just faster or does compile the regex differently I can't tell. However I narrowed the problem down to the following part:

`([a-zA-Z0-9_\-\+\~\^\{\}]+[\.]?)+`

The problem is the nested quantifiers which seem to lead to a backtracking loop. The problem is outlined here quite good: http://www.regular-expressions.info/catastrophic.html

Looking at the specific part it seems to be wrong anyhow. What you are trying to achieve is that the mail address must start with a given character class EXCLUDING the dot and then a dot may follow. This pattern then shall repeat.

To avoid the backtracking issue the regex could just be broken down like this:

`/^([a-zA-Z0-9_\-\+\~\^\{\}]+[\.]?)+@{1}([a-zA-Z0-9_\-\+\~\^\{\}]+[\.]?)+\.[A-Za-z0-9]{2,}$/`

will get 

`/^[a-zA-Z0-9_\-\+\~\^\{\}]\.?[a-zA-Z0-9_\-\+\~\^\{\}\.]+@[a-zA-Z0-9_\-\+\~\^\{\}]\.?[a-zA-Z0-9_\-\+\~\^\{\}\.]+\.[A-Za-z0-9]{2,}$/`

Note that I just expanded the regex to avoid a backtracking case. I also changed the character class containing just the dot **[\.]** to a simple escaped dot: **\.** and removed the {1} quantifier after the @ sign.
Still this regex will not reject clearly wrong emails like a dot right before the @ sign.

However, still many problems with the regex persist. Technically allowed characters like the ! are rejected. According to wikipedia and the RFC this char may very well occur.

I found this tool to be a reasonable helper: http://isemail.info/test%21a%40google.de

My solution to this problem was to disable email validation through zebra and bundle the PHP-library from isemail.info

**Comment by stefangabos** [comment]
I've done more checks myself and, for now, I ended up doing the following things:
- reject email addresses containing consecutive dots
- reject email addresses longer than 255 characters
- apply the following regular expression (much faster than the previous one) otherwise
```
/^[a-z0-9_\-\+\~\^\{\}\.]{1,64}@([a-z0-9_\-\+\~\^\{\}\.]{1,255}\.[a-z0-9]{2,}$/i
```

**Comment by ArneTR** [comment]
I'm really sorry to be so critical, but I really don't get where this is going?!

I outlined in my post before that I think this regex should not be used in this way, because it allows false email addresses to be validated and, which is far more problematic, rejects correct email addresses.

To my understanding the absolute requirement for a validation library should be to NOT generate false-negatives. When this task is achieved the next task should be to get the false-positive-rate down.

As I said before, this regex rejects an email with a ! in it. example: test!a@google.de is a VALID email.

Then, even after your hotfix, this email would be validated as true, which is NOT correct: .@google.de


Trying to solve this problem with regex seems neither reasonable nor solvable at all. Looking at this post: http://stackoverflow.com/questions/201323/using-a-regular-expression-to-validate-an-email-address the there seems to be a PCRE-Regex that is RFC compliant. However, Javascript can NOT do it.

So I really only see one solution to this problem: Applying a more relaxed regex for the frontend which does NOT generate false-negatives. Then apply a concise and complete checking mechanism (either by using the RFC-compliant regex from the aforementioned article or by bundling a 3rd party library) to check on the server-side.

I hope this critic doesn't come top harsh, and to be fair your regex should work for more than 90% of real world problems, maybe even 99%. But I really think using this regex which is not entirely correct is a wrong approach ... especially when a full fledged solution is in reach.

**Comment by stefangabos** [comment]
I already said that this is not RFC compliant. I don't care about those other characters. As I don't care about more other characters and I'm also considering removing curly brackets and other characters, as in real life I am not expecting those. I am *not* making a RFC compliant email validator :) 

What I wanted is that the validator doesn't choke anymore when bogus stuff it's thrown at it. 

No hardfeeling ;) 

Thanks for the feedback!
