### ISSUE TITLE
Illegal string offset 'class'

### ISSUE THREAD

**Issue by jasondegn** [stefangabos/Zebra_Form#37]
After upgrading from PHP 7.0.x to 7.1.5 in our test environment, we are seeing multiple errors in our pages using Zebra_Form. We are running the latest code (2.9.8) and the pages to do not render properly.

[22-May-2017 07:33:21 America/Chicago] PHP Warning:  Illegal string offset 'class' in <path>\Zebra_Form\Zebra_Form.php on line 1187

**Comment by stefangabos** [comment]
Should be fixed now - just replace Zebra_Form.php

**Comment by stefangabos** [comment]
Is it ok now? Can this be closed?

**Comment by jasondegn** [comment]
Yes!! Thanks so much!!

Sent from my iPhone

On May 23, 2017, at 5:34 AM, Stefan Gabos <notifications@github.com<mailto:notifications@github.com>> wrote:


Is it ok now? Can this be closed?

-
