### ISSUE TITLE
Hidden input type

### ISSUE THREAD

**Issue by userc479** [stefangabos/Zebra_Form#42]
Hello again, I want to be able to use the hidden input type field but you state it will be the same name as the hidden field but if I want to use Google Captcha V3 which requires hidden input type and it has to be like the following:

`<input type="hidden" name="recaptcha_response" id="recaptchaResponse">`

As it can't have value and have tried doing your form approach but it's not responding back with response - any help please.

**Comment by stefangabos** [comment]
i haven't tested but it should be something like
$obj = $form->add('hidden', 'recaptcha_response');
$obj->set_attributes(array('id' => 'recaptchaResponse'));

**Comment by userc479** [comment]
Yup - that works - fantastic - thank you! :)
